apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: qdrant
spec:
  clusterIP: None
  selector:
    app: qdrant
  ports:
    - name: http
      port: 6333
      targetPort: 6333
    - name: p2p
      port: 6334
      targetPort: 6334

